---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-hub
  namespace: test-ns-hub
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        agentpool: npuser01
      containers:
      - name: nginx
        image: acrakszup2kwh4fwbse.azurecr.io/test-ns-hub/nginx:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
