name: Deploy an app to AKS

on:
  workflow_dispatch:
#    inputs:
#      environment:
#        type: choice
#        description: Select Environment variables
#        required: true
#        options:
#        - dev
#        - prod
#      image_name:  
#        description: Input image name
#        required: true
#      tag:
#        description: Input image tag
#        required: true

#      image_tag:
#        description: Input base image tag
#        required: true
#        default: v1     

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy to AKS
#    environment: ${{ github.event.inputs.environment }}
    environment: dev
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install kubelogin for non-interactive login
      run: |
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.20/kubelogin-linux-amd64.zip
        sudo unzip -j kubelogin-linux-amd64.zip -d /usr/local/bin
        rm -f kubelogin-linux-amd64.zip
        kubelogin --version

    - name: set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER }}
        admin: false
        use-kubelogin: true
        
    - name: run kubectl command
      run: |
        kubectl config set-context --current --namespace=github-test
        kubectl get pods
        
