name: OIDC Demo

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
#    - uses: actions/checkout@v2

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#        allow-no-subscriptions: true
#    - name: 'Run az commands'
#      run: |
#        az account show
#        az group list

#    - name: Set up kubelogin for non-interactive login
#      run: |
#        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
#        sudo unzip -j kubelogin-linux-amd64.zip -d /usr/local/bin
#        rm -f kubelogin-linux-amd64.zip
#        kubelogin --version

#    - name: set AKS context
#      uses: azure/aks-set-context@v3
#      with:
#        resource-group: $$ {{ secrets.AKS_RESOURCE_GROUP }}
#        cluster-name: $${{ secrets.AKS_CLUSTER }}
#        admin: false
#        use-kubelogin: true
        
