name: Build a docker image

on:
  workflow_dispatch:
  
jobs:
  steps:
    - name: Checkout
      uses: actions/checkoout@v3
      
    - name: Build docker image
      run: |
        docker build . --file Dockerfile --tag dummp:v1.0
