name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ "main" ]
  
jobs:

  build:
    name: Build a docker image
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag dummp:$(date +%s)
